version: "2.2"
services:
  MySQL:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: jm_oldc
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./sqldata:/var/lib/mysql
    ports:
      - 3306:3306